# Low level configuration for how the `poetry` tool should work for this project.
# You should rarely need to change this. See `pyproject.toml` for the primary project configuration.

[virtualenvs]
create = false  # Prevents Poetry from creating its own virtualenv
in-project = false  # Disables the .venv in project directory
prefer-active-python = true  # Uses the active Python interpreter (from Conda)

[repositories]
# If you need custom package repositories, add them here
